name: PHP Composer

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Validate composer.json and composer.lock
        uses: firehed/lint-php-action@v1
      - name: Install dependencies
        run: composer install --prefer-dist --no-progress
      - name: PHPUnit
        uses: chindit/actions-phpunit@master
